name: Trigger Site Rebuild on a CRON Schedule

on:
  schedule:
    - cron: '*/30 * * * *'
  push:
    branches:
      - 'main'

jobs:
  cron:
    name: Push Docker image to multiple registries
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
        with:
          # repo and workload scopes
          token: ${{ secrets.PAT }}

      - name: get tag
        run: git tag

      - name: get tag remote
        run: git ls-remote --tags

      - name: get version
        run: ./get-versions.sh

      - name: github env
        run: echo $GITHUB_ENV

      - name: version
        run: echo "version=$(cat version)" >> $GITHUB_ENV
      - name: build
        run: echo "build=$(cat build)" >> $GITHUB_ENV

      - name: github env
        run: echo $GITHUB_ENV

      - name: version
        run: echo {{ env.version }}

      - name: github env
        run: echo $GITHUB_ENV

      - name: version
        id: version
        run: cat version
      - name: build
        id: build
        run: cat build

      - name: time
        run: date > time.txt

      - name: tag_msg
        id: tag_msg
        run: echo "::set-output name=vtest::v$(cat version)-$(cat build)"

      - name: commit_msg
        id: commit_msg
        run: echo "::set-output [AUTO] publish multipaper v$(cat version)-$(cat build)"

      - name: test
        run: echo ${{steps.commit_msg.outputs.stdout}}

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: ${{steps.commit_msg.outputs.stdout}}
          tagging_message: ${{steps.tag_msg.outputs.vtest}}
          # commit_message: Automated Change

