name: Trigger Site Rebuild on a CRON Schedule

on:
  schedule:
    - cron: '*/1 * * * *'

jobs:
  push_to_registries:
    name: Push Docker image to multiple registries
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: pwd
        run: pwd
      - name: ls
        run: ls
      - name: export
        run: export

