name: Trigger Site Rebuild on a CRON Schedule

on:
  schedule:
    - cron: '*/30 * * * *'
  push:
    branches:
      - 'main'

jobs:
  cron:
    name: Push Docker image to multiple registries
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
        with:
          # repo and workload scopes
          token: ${{ secrets.PAT }}

      - name: get tag
        run: git tag

      - name: get tag remote
        run: git ls-remote --tags

      - name: get version
        run: ./get-versions.sh

      - name: version
        run: |
          echo "VERSION: ${{ env.VERSION }}"
          echo "BUILD: ${{ env.BUILD }}"
          echo "MASTER_VERSION: ${{ env.MASTER_VERSION }}"
          echo "SERVER_VERSION: ${{ env.SERVER_VERSION }}"

          #      - name: info
          #        id: info
          #        run: |
          #          echo "::set-output name=tagging_message::v$(cat version)-$(cat build)"
          #          echo "::set-output name=commit_message::[AUTO] publish multipaper v$(cat version)-$(cat build)"
          #

      - name: auto commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          # repo and workload scopes
          tagging_message: "${{ env.SERVER_VERSION }}"
          commit_message: "[AUTO] multipaper server ${{ env.SERVER_VERSION }}"

