name: Trigger Site Rebuild on a CRON Schedule

on:
  # schedule:
  #   - cron: '*/30 * * * *'
  push:
    branches:
      - 'main'

permissions:
  contents: write

jobs:
  cron:
    name: Push Docker image to multiple registries
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - name: pwd
        run: pwd
      - name: ls
        run: ls
      - name: export
        run: export
      - name: time
        run: date > time.txt
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Automated Change
