name: Trigger Site Rebuild on a CRON Schedule

on:
  # schedule:
  #   - cron: '*/30 * * * *'
  push:
    branches:
      - 'main'

jobs:
  cron:
    name: Push Docker image to multiple registries
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
        with:
          # repo and workload scopes
          token: ${{ secrets.PAT }}
      - name: pwd
        run: pwd
      - name: ls
        run: ls
      - name: export
        run: export

      - name: get version
        run: . ./get-versions.sh
      - name: version
        id: version
        run: echo $version
      - name: build
        id: build
        run: echo $build

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Automated Change
          branch: feature-123-${{ steps.version.outputs.msg }}
          tagging_message: v${{ steps.version.outputs.msg }}-${{ steps.build.outputs.msg }}
          create_branch: true

