name: Publish Docker image

on:
  push:
    branches:
      - 'main'

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: version
        run: |
          echo "BUILD=$(cat server/tags | cut -d'-' -f2)" >> $GITHUB_ENV
          echo "VERSION=$(cat server/tags | cut -d'-' -f1)" >> $GITHUB_ENV
          echo "SERVER_VERSION=$(cat server/tags)" >> $GITHUB_ENV
          echo "MASTER_VERSION=$(cat master/tags)" >> $GITHUB_ENV

      - name: tagging
        run: |
          echo "SERVER_TAG=akiicat/test:latest,akiicat/test:${{ env.SERVER_VERSION }},akiicat/test:${{ env.VERSION }}" >> $GITHUB_ENV
          echo "MASTER_TAG=akiicat/test:latest,akiicat/test:${{ env.MASTER_VERSION }}" >> $GITHUB_ENV

      - name: Build Multipaper Master and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: master
          push: true
          tags: ${{ env.MASTER_TAG }}
          labels: master

      - name: Build Multipaper Server and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: server
          push: true
          tags: ${{ env.SERVER_TAG }}
          labels: server
